version: '3.9'

services:

  family_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: family_db
      MYSQL_USER: family
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql/family:/var/lib/mysql

  family_rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - "5672:5672" #AMQP
      - "15672:15672" #MGMT

  idp_postgres:
    image: postgres:15.4-alpine
    volumes:
      - ./bmac/idp/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password



  idp_keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=idp_postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
    command: start-dev
    ports:
      - "8180:8080"
    depends_on:
      - idp_postgres
